In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
print(np.__version__)

1.20.1


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.n)